# Generated by Django 5.2.6 on 2025-09-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='My Shop', max_length=200)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/')),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers', max_length=10)),
                ('inventory_password_hash', models.CharField(blank=True, help_text='Password for inventory access', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Profile',
                'verbose_name_plural': 'Shop Profiles',
            },
        ),
    ]
