# Generated by Django 5.2.6 on 2025-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='last_invoice_number',
            field=models.IntegerField(default=0, help_text='Last generated invoice number'),
        ),
    ]
