# Generated by Django 5.2.6 on 2025-09-24 12:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label_width_mm', models.FloatField(help_text='Label width in millimeters')),
                ('label_height_mm', models.FloatField(help_text='Label height in millimeters')),
                ('columns', models.IntegerField(default=1, help_text='Number of columns on sheet')),
                ('rows', models.IntegerField(default=1, help_text='Number of rows on sheet')),
                ('margin_top_mm', models.FloatField(default=5.0)),
                ('margin_left_mm', models.FloatField(default=5.0)),
                ('margin_right_mm', models.FloatField(default=5.0)),
                ('margin_bottom_mm', models.FloatField(default=5.0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Barcode Label Template',
                'verbose_name_plural': 'Barcode Label Templates',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, unique=True)),
                ('barcode_value', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price_incl_tax', models.DecimalField(decimal_places=2, help_text='Price including tax', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Tax rate percentage', max_digits=5)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('track_stock', models.BooleanField(default=True, help_text='Whether to track stock for this product')),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('hsn', models.CharField(blank=True, help_text='HSN/SAC Code', max_length=20, null=True)),
                ('unit', models.CharField(default='pcs', help_text='Unit of measurement', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_change', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('reason', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Stock Adjustment'), ('return', 'Return'), ('damage', 'Damage/Loss')], default='adjustment', max_length=20)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Unit cost for purchases', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference', models.CharField(blank=True, help_text='Reference like invoice number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-timestamp'],
            },
        ),
    ]
