# Generated by Django 5.2.6 on 2025-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Current stock quantity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='qty_change',
            field=models.DecimalField(decimal_places=3, help_text='Positive for stock in, negative for stock out', max_digits=10),
        ),
    ]
